name: stud_ticket_CI

on:
  push:
    branches: [ master ]

jobs:
  clone_and_compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn package -Dmaven.test.skip -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      # Run mvn package without tests (db connection necessity cause error), and [Progress] logs ignored
      
    
    - name: check dirs
      run: |
        pwd
        ls- l
        cd target
        pwd 
        ls -l
    
    ### Request Timeout error ### 
    - name: copy file via ssh password   
      uses: appleboy/scp-action@master
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USERNAME }}
       password: ${{ secrets.PASSWORD }}
       port: ${{ secrets.PORT }}
       source: "target/student-card-0.0.1-SNAPSHOT.jar"
       target: ""
    
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
#        port: ${{ secrets.PORT }}
#        script: restart
     
