name: stud_ticket_CI

on:
  push:
    branches: [ master ]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  compile:
    runs-on: ubuntu-latest
    needs: [clone]
    steps:
      - name: compile sources
        run:
          mvn compile
